<?php

namespace Database\Seeders;

use App\Models\EproKursus;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KursusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $senaraiKursus = [
            ['kur_id' => 1, 'kur_nama' => 'Kursus Pengurusan Pelanggan Berkualiti', 'kur_objektif' => '<ol><li>Mengetahui kepentingan perkhidmatan pelanggan berkualiti dalam meningkatkan sistem penyampaian;</li><li>Mengetahui ciri-ciri petugas barisan hadapan yang berketerampilan dan berkomunikasi secara secara berkesan dalam memberi perkhidmatan yang memenuhi keperluan pelanggan; dan</li><li>Mengenalpasti kaedah pengendalian telefon dan pengurusan kaunter yang berkesan.</li></ol>', 'kur_idkategori' => 1, 'kur_idpenganjur' => 1, 'kur_tkhmula' => '2020-04-01', 'kur_msamula' => '08:00 AM', 'kur_tkhtamat' => '2020-04-02', 'kur_msatamat' => '05:00 PM', 'kur_bilhari' => 2, 'kur_idtempat' => 1, 'kur_tkhbuka' => '2020-02-01', 'kur_tkhtutup' => '2020-03-18', 'kur_tkhmbalas' => '2020-03-20', 'kur_bilpeserta' => 50, 'kur_idkumpulan' => 4, 'kur_status' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['kur_id' => 2, 'kur_nama' => 'KURSUS KETAHUI CUTI DAN PENCEN ANDA', 'kur_objektif' => '<ul><li>Memberi pendedahan kepada pegawai berkenaan jenis-jenis cuti yang terdapat di dalam perkhidmatan awam; dan</li><li>Mempertingkatkan pengetahuan mengenai cuti dan pengurusan pencen sebagai penjawat awam.</li></ul>', 'kur_idkategori' => 1, 'kur_idpenganjur' => 1, 'kur_tkhmula' => '2020-09-02', 'kur_msamula' => '08:00 AM', 'kur_tkhtamat' => '2020-09-03', 'kur_msatamat' => '05:00 PM', 'kur_bilhari' => 2, 'kur_idtempat' => 1, 'kur_tkhbuka' => '2020-07-24', 'kur_tkhtutup' => '2020-08-10', 'kur_tkhmbalas' => '2020-08-28', 'kur_bilpeserta' => 40, 'kur_idkumpulan' => 4, 'kur_status' => 1, 'created_at' => now(), 'updated_at' => now(),],
            ['kur_id' => 3, 'kur_nama' => 'KURSUS ONLINE: PENGURUSAN PELANGGAN BERKUALITI', 'kur_objektif' => '<ul><li>Mengetahui kepentingan perkhidmatan elanggan berkualiti dalam meningkatkan sistem penyampaian;<li>Mengetahui ciri-ciri petugas barisan hadapan yang berketerampilan dan berkomunikasi secara secara berkesan dalam memberi perkhidmatan yang memenuhi keperluan pelanggan; dan    <li>Mengenalpasti kaedah pengendalian telefon dan engurusan kaunter yang berkesan.', 'kur_idkategori' => 1, 'kur_idpenganjur' => 1, 'kur_tkhmula' => '2020-07-01', 'kur_msamula' => '08:30 AM', 'kur_tkhtamat' => '2020-07-01', 'kur_msatamat' => '04:30 PM', 'kur_bilhari' => 1, 'kur_idtempat' => 5, 'kur_tkhbuka' => '2020-06-01', 'kur_tkhtutup' => '2020-06-15', 'kur_tkhmbalas' => '2020-06-22', 'kur_bilpeserta' => 20, 'kur_idkumpulan' => 4, 'kur_status' => 0, 'created_at' => now(), 'updated_at' => now(),],
            ['kur_id' => 4, 'kur_nama' => 'KURSUS JOM BELAJAR GUNA MEETING APPS', 'kur_objektif' => 'Memahami dan mempelajari <em>tools</em> setiap aplikasi bagi kegunaan mesyuarat dan kursus', 'kur_idkategori' => 3, 'kur_idpenganjur' => 1, 'kur_tkhmula' => '2020-08-11', 'kur_msamula' => '08:30 AM', 'kur_tkhtamat' => '2020-08-11', 'kur_msatamat' => '04:30 PM', 'kur_bilhari' => 1, 'kur_idtempat' => 5, 'kur_tkhbuka' => '2020-06-29', 'kur_tkhtutup' => '2020-07-16', 'kur_tkhmbalas' => '2020-08-06', 'kur_bilpeserta' => 20, 'kur_idkumpulan' => 4, 'kur_status' => 0, 'created_at' => now(), 'updated_at' => now(),],
            ['kur_id' => 5, 'kur_nama' => 'KURSUS ASAS FOTOGRAFI &amp; PENYUNTINGAN', 'kur_objektif' => '<ul><li>Meningkatkan kemahiran dan pengetahuan mengenai teknik-teknik tertentu dalam menghasilkan gambar yang berkualiti; dan<li>Mempelajari teknik video editing yang mudah dan menarik</li></ul>', 'kur_idkategori' => 3, 'kur_idpenganjur' => 1, 'kur_tkhmula' => '2020-07-27', 'kur_msamula' => '08:30 AM', 'kur_tkhtamat' => '2020-07-28', 'kur_msatamat' => '04:30 PM', 'kur_bilhari' => 2, 'kur_idtempat' => 1, 'kur_tkhbuka' => '2020-07-03', 'kur_tkhtutup' => '2020-07-17', 'kur_tkhmbalas' => '2020-07-24', 'kur_bilpeserta' => 30, 'kur_idkumpulan' => 4, 'kur_status' => 0, 'created_at' => now(), 'updated_at' => now(),],
            ['kur_id' => 6, 'kur_nama' => 'KURSUS PENGURUSAN STRES', 'kur_objektif' => '<ul><li><strong>Mengelakkan para peserta untuk meneliti keadaan stres/emosi diri; dan</li></strong></ul><ul><li><strong>Mendedahkan kepada para peserta tentang cara pengurusan stres/emosi diri yang berkesan.</li></ul></strong>', 'kur_idkategori' => 5, 'kur_idpenganjur' => 1, 'kur_tkhmula' => '2020-08-17', 'kur_msamula' => '10:00 AM', 'kur_tkhtamat' => '2020-08-19', 'kur_msatamat' => '12:30 PM', 'kur_bilhari' => 3, 'kur_idtempat' => 8, 'kur_tkhbuka' => '2020-07-08', 'kur_tkhtutup' => '2020-07-24', 'kur_tkhmbalas' => '2020-07-30', 'kur_bilpeserta' => 25, 'kur_idkumpulan' => 4, 'kur_status' => 0, 'created_at' => now(), 'updated_at' => now(),],
            ['kur_id' => 7, 'kur_nama' => 'KURSUS PROTOKOL, ETIKET SOSIAL DAN PENGURUSAN MAJLIS', 'kur_objektif' => '<ul><li>Menyenaraikan teori dan amalan protokol dan etiket sosial serta elemen pengurusan majlis serta mengaplikasikan kaedah dan tatacara protokol dan etiket sosial yang betul;</li><li>Memahami mengenai kekananan tempat duduk, bendera, gambar dan logo dengan betul; dan</li><li>Memahami dan mengaplikasi cara mengurus pelbagai majlis berasaskan konsep, etiket dan amalan protokol.</li></ul>', 'kur_idkategori' => 3, 'kur_idpenganjur' => 1, 'kur_tkhmula' => '2020-08-24', 'kur_msamula' => '03:00 PM', 'kur_tkhtamat' => '2020-08-26', 'kur_msatamat' => '01:00 PM', 'kur_bilhari' => 3, 'kur_idtempat' => 6, 'kur_tkhbuka' => '2020-07-17', 'kur_tkhtutup' => '2020-08-03', 'kur_tkhmbalas' => '2020-08-07', 'kur_bilpeserta' => 40, 'kur_idkumpulan' => 4, 'kur_status' => 0, 'created_at' => now(), 'updated_at' => now(),],
            ['kur_id' => 8, 'kur_nama' => 'PROGRAM CINTA ILMU SIRI 1: SMART AL-QURAN', 'kur_objektif' => '<ul><li>Mendedahkan kepada peserta mengenai kepentingan mempelajari Al-Quran;</li></ul><ul><li>Mendedahkan mengenai ilmu-ilmu Al-Quran dan asas tahsin ; dan</li></ul><ul><li>Menarik minat peserta mengenai keindahan tadabbur Al-Quran.</li></ul>', 'kur_idkategori' => 4, 'kur_idpenganjur' => 1, 'kur_tkhmula' => '2020-08-12', 'kur_msamula' => '08:30 AM', 'kur_tkhtamat' => '2020-08-12', 'kur_msatamat' => '04:30 PM', 'kur_bilhari' => 1, 'kur_idtempat' => 3, 'kur_tkhbuka' => '2020-07-14', 'kur_tkhtutup' => '2020-07-23', 'kur_tkhmbalas' => '2020-07-30', 'kur_bilpeserta' => 25, 'kur_idkumpulan' => 4, 'kur_status' => 0, 'created_at' => now(), 'updated_at' => now(),],
            ['kur_id' => 9, 'kur_nama' => 'KURSUS BAHASA MANDARIN', 'kur_objektif' => '<ul><li>Menggalakkan pembelajaran Bahasa Mandarin sebagai bahasa tambahan;</li>    <li>Meningkatkan keyakinan dan kemahiran diri peserta dalam mempelajari Bahasa Mandarin; dan</li>    <li>Melatih penguasaan Bahasa Mandarin dengan membantu peserta berkomunikasi menggunakan Bahasa Mandarin</li></ul>', 'kur_idkategori' => 3, 'kur_idpenganjur' => 1, 'kur_tkhmula' => '2020-09-28', 'kur_msamula' => '08:30 AM', 'kur_tkhtamat' => '2020-10-02', 'kur_msatamat' => '04:30 PM', 'kur_bilhari' => 5, 'kur_idtempat' => 1, 'kur_tkhbuka' => '2020-08-17', 'kur_tkhtutup' => '2020-09-11', 'kur_tkhmbalas' => '2020-09-18', 'kur_bilpeserta' => 50, 'kur_idkumpulan' => 4, 'kur_status' => 0, 'created_at' => now(), 'updated_at' => now(),],
            ['kur_id' => 10, 'kur_nama' => 'PROGRAM PEMANTAPAN AKRAB', 'kur_objektif' => '<ul><li>Memberikan pendedahan kepada ahli AKRAB tentang kemahiran yang baharu dalam proses menolong; dan</li><li>Mempertingkatkan kemahiran menolong di antara ahli AKRAB.</li></ul>', 'kur_idkategori' => 5, 'kur_idpenganjur' => 1, 'kur_tkhmula' => '2020-10-06', 'kur_msamula' => '09:00 AM', 'kur_tkhtamat' => '2020-10-07', 'kur_msatamat' => '04:30 PM', 'kur_bilhari' => 2, 'kur_idtempat' => 1, 'kur_tkhbuka' => '2020-09-14', 'kur_tkhtutup' => '2020-09-25', 'kur_tkhmbalas' => '2020-09-30', 'kur_bilpeserta' => 50, 'kur_idkumpulan' => 6, 'kur_status' => 0, 'created_at' => now(), 'updated_at' => now(),],
            ['kur_id' => 11, 'kur_nama' => 'KELAS BIMBINGAN AGAMA SIRI 2:FIQH WANITA DARAH', 'kur_objektif' => 'Mempelajari ilmu agama dalam pelbagai bidang secara bersiri.', 'kur_idkategori' => 4, 'kur_idpenganjur' => 1, 'kur_tkhmula' => '2020-08-27', 'kur_msamula' => '09:30 AM', 'kur_tkhtamat' => '2020-08-27', 'kur_msatamat' => '11:30 AM', 'kur_bilhari' => 1, 'kur_idtempat' => 11, 'kur_tkhbuka' => '2020-07-27', 'kur_tkhtutup' => '2020-08-14', 'kur_tkhmbalas' => '2020-08-21', 'kur_bilpeserta' => 25, 'kur_idkumpulan' => 4, 'kur_status' => 0, 'created_at' => now(), 'updated_at' => now(),],
            ['kur_id' => 12, 'kur_nama' => 'PROGRAM CINTA ILMU SIRI 2: BIO TERAPI SOLAT', 'kur_objektif' => '<ul><li>Memberi pendedahan dan kefahaman kepada peserta mengenai persoalan saintifik dan pelaksanaan solat;</li></ul><ul><li>Memperbetulkan teknik pergerakan di dalam solat berdasarkan Al-Quran dan As-Sunnah dan kaitannya dengan terapi, pencegahan dan rawatan bagi pelbagai penyakit; dan</li></ul><ul><li>Membantu meningkatkan kualiti ibadah dan kesihatan.</li></ul>', 'kur_idkategori' => 4, 'kur_idpenganjur' => 1, 'kur_tkhmula' => '2020-09-09', 'kur_msamula' => '08:30 AM', 'kur_tkhtamat' => '2020-09-10', 'kur_msatamat' => '04:30 PM', 'kur_bilhari' => 2, 'kur_idtempat' => 1, 'kur_tkhbuka' => '2020-07-29', 'kur_tkhtutup' => '2020-08-14', 'kur_tkhmbalas' => '2020-08-21', 'kur_bilpeserta' => 60, 'kur_idkumpulan' => 4, 'kur_status' => 0, 'created_at' => now(), 'updated_at' => now(),],
            ['kur_id' => 13, 'kur_nama' => 'KURSUS VIDEO DAN PENYUNTINGAN KREATIF', 'kur_objektif' => '<ul><li>Meningkatkan kemahiran dan pengetahuan sedia ada dalam bidang rakaman video;</li><li>Memberi pendedahan kepada peserta cara mendapatkan rakaman video yang kreatif dan terbaik sama ada menggunakan kamera video, DLSR video ataupun <em>smartphone</em>;</li><li>Memahami keseluruhan proses pembikinan video yang menarik; dan</li><li>Mempelajari teknik penyuntingan yang melibatkan suara latar, grafik dan<em> audio effect</em> dalam menjadikan video yang menarik.</li></ul>', 'kur_idkategori' => 3, 'kur_idpenganjur' => 1, 'kur_tkhmula' => '2020-09-21', 'kur_msamula' => '03:00 PM', 'kur_tkhtamat' => '2020-09-23', 'kur_msatamat' => '01:00 PM', 'kur_bilhari' => 3, 'kur_idtempat' => 12, 'kur_tkhbuka' => '2020-09-01', 'kur_tkhtutup' => '2020-09-09', 'kur_tkhmbalas' => '2020-09-11', 'kur_bilpeserta' => 35, 'kur_idkumpulan' => 4, 'kur_status' => 0, 'created_at' => now(), 'updated_at' => now(),],
            ['kur_id' => 14, 'kur_nama' => 'PROGRAM &quot;HAI! APA KHABAR?&quot;', 'kur_objektif' => '<ul><li>Mendedahkan kepada peserta tentang kepentingan kewangan; <li>Menyampaikan maklumat tentang risiko bertingkah laku yang mengakibatkan gangguan seksual dan; <li> Menyediakan ruang untuk peserta berkomunikasi secara terbuka.', 'kur_idkategori' => 5, 'kur_idpenganjur' => 1, 'kur_tkhmula' => '2021-03-09', 'kur_msamula' => '09:30 AM', 'kur_tkhtamat' => '2021-03-09', 'kur_msatamat' => '11:30 AM', 'kur_bilhari' => 2, 'kur_idtempat' => 5, 'kur_tkhbuka' => '2021-02-25', 'kur_tkhtutup' => '2021-03-04', 'kur_tkhmbalas' => '2021-03-05', 'kur_bilpeserta' => 30, 'kur_idkumpulan' => 7, 'kur_status' => 0, 'created_at' => now(), 'updated_at' => now(),],

        ];

        foreach ($senaraiKursus as $kursus) {
            EproKursus::create($kursus);
        }
    }
}
